//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"

	"github.com/oapi-codegen/runtime"
)

// Defines values for ToolCallType.
const (
	Function ToolCallType = "function"
)

// ChatRequest defines model for ChatRequest.
type ChatRequest struct {
	// Message User message to send to the AI
	Message string `json:"message"`

	// Model Model to use - gpt-5, supermind-agent-v1, deepseek, etc.
	Model *string `json:"model,omitempty"`
}

// ChatResponse defines model for ChatResponse.
type ChatResponse struct {
	// Content AI response content
	Content       *string         `json:"content,omitempty"`
	SearchResults *SearchResponse `json:"search_results,omitempty"`

	// ToolCalls Tool calls requested by the model
	ToolCalls *[]ToolCall `json:"tool_calls,omitempty"`
}

// HelloResponse defines model for HelloResponse.
type HelloResponse struct {
	Message string `json:"message"`
}

// PageReaderRequest defines model for PageReaderRequest.
type PageReaderRequest struct {
	// Url URL of the webpage to read
	Url string `json:"url"`
}

// PageReaderResponse defines model for PageReaderResponse.
type PageReaderResponse struct {
	// Content Extracted text content from the webpage
	Content *string `json:"content,omitempty"`

	// Error Error message if fetch failed
	Error *string `json:"error,omitempty"`

	// Url The URL that was fetched
	Url *string `json:"url,omitempty"`
}

// SearchError defines model for SearchError.
type SearchError struct {
	// Error Error message
	Error *string `json:"error,omitempty"`

	// Keyword The keyword that failed
	Keyword *string `json:"keyword,omitempty"`
}

// SearchQueryResult defines model for SearchQueryResult.
type SearchQueryResult struct {
	// Keyword The search keyword
	Keyword *string `json:"keyword,omitempty"`

	// Response Search response data
	Response *map[string]interface{} `json:"response,omitempty"`
}

// SearchRequest defines model for SearchRequest.
type SearchRequest struct {
	// Keywords Search keywords
	Keywords []string `json:"keywords"`

	// MaxResults Maximum number of results per keyword
	MaxResults *int `json:"max_results,omitempty"`
}

// SearchResponse defines model for SearchResponse.
type SearchResponse struct {
	// CombinedAnswer Combined answer from search results
	CombinedAnswer *string              `json:"combined_answer,omitempty"`
	Errors         *[]SearchError       `json:"errors,omitempty"`
	Queries        *[]SearchQueryResult `json:"queries,omitempty"`
}

// ToolCall defines model for ToolCall.
type ToolCall struct {
	Function ToolCallFunction `json:"function"`

	// Id Unique identifier for the tool call
	Id string `json:"id"`

	// Type The type of tool call
	Type ToolCallType `json:"type"`
}

// ToolCallType The type of tool call
type ToolCallType string

// ToolCallFunction defines model for ToolCallFunction.
type ToolCallFunction struct {
	// Arguments JSON-encoded arguments for the function
	Arguments string `json:"arguments"`

	// Name The name of the function to call
	Name string `json:"name"`
}

// GetHelloParams defines parameters for GetHello.
type GetHelloParams struct {
	// Name Name to greet
	Name string `form:"name" json:"name"`
}

// PostChatJSONRequestBody defines body for PostChat for application/json ContentType.
type PostChatJSONRequestBody = ChatRequest

// PostPageReaderJSONRequestBody defines body for PostPageReader for application/json ContentType.
type PostPageReaderJSONRequestBody = PageReaderRequest

// PostSearchJSONRequestBody defines body for PostSearch for application/json ContentType.
type PostSearchJSONRequestBody = SearchRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Chat with AI
	// (POST /chat)
	PostChat(w http.ResponseWriter, r *http.Request)
	// Say hello
	// (GET /hello)
	GetHello(w http.ResponseWriter, r *http.Request, params GetHelloParams)
	// Read and extract text from a webpage
	// (POST /page_reader)
	PostPageReader(w http.ResponseWriter, r *http.Request)
	// Search the web
	// (POST /search)
	PostSearch(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostChat operation middleware
func (siw *ServerInterfaceWrapper) PostChat(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostChat(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHello operation middleware
func (siw *ServerInterfaceWrapper) GetHello(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetHelloParams

	// ------------- Required query parameter "name" -------------

	if paramValue := r.URL.Query().Get("name"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "name"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "name", r.URL.Query(), &params.Name)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHello(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostPageReader operation middleware
func (siw *ServerInterfaceWrapper) PostPageReader(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostPageReader(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostSearch operation middleware
func (siw *ServerInterfaceWrapper) PostSearch(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostSearch(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/chat", wrapper.PostChat)
	m.HandleFunc("GET "+options.BaseURL+"/hello", wrapper.GetHello)
	m.HandleFunc("POST "+options.BaseURL+"/page_reader", wrapper.PostPageReader)
	m.HandleFunc("POST "+options.BaseURL+"/search", wrapper.PostSearch)

	return m
}
